name: rir-reconstruction
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - flask=2.3.2
  - pytorch=2.0.1
  - pytorch-lightning=2.0.9
  - numpy=1.24.4
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - libsndfile=1.2.2
  - pip
  - pip:
      - soundfile==0.12.1
      - joblib==1.3.2
